# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f28cafd31c48d7cb282f59f74184701060af1ae157778f5a88c059de819d8492bb4aba72b5663e47e48fe2dee7aa6d7dc39e45323c6b82bd87f2d34edaf3831

test:
  secret_key_base: ad15330b1ab62e3316607a0f7f015c7316886a165c016213ab3048669dc0120f9b6e976dadb652b1f14713cd5d497b0ab6d147bd0b33f3bba20b1c00415c92c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
